[package]
name = "invaders"
version = "0.1.0"
authors = ["Nathan Stocks <cleancut@github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.4"
image = "0.24.3"
num-complex = "0.4.2"
